#pragma once
#include "NativeGameplayTags.h"

namespace FBCTags
{
	// Movement
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SprintingBlocked);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RunningBlocked);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouching);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Airborne);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AimingDownSights);

	// Items
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxResourceRecoverable);

	// Abilities
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FireWeapon);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityDamage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Build);

	// Input
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputFireDown);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputFireReleased);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputAltFireDown);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputAltFireReleased);

}
